### ISSUE TITLE
Invariant Violation: requireNativeComponent: "CMIFColorMatrixImageFilter" was not found in the UIManager.

### ISSUE THREAD

**Issue by lirongNISL** [iyegoroff/react-native-color-matrix-image-filters#103]
"react": "17.0.2",
    "react-native": "0.64.2",
    "react-native-color-matrix-image-filters": "^6.0.3",

after install react-native-color-matrix-image-filters the error information is under like that

"Invariant Violation: requireNativeComponent: "CMIFColorMatrixImageFilter" was not found in the UIManager.

This error is located at:
    in CMIFColorMatrixImageFilter
    in ColorMatrixImageFilter
    in Unknown (created by MyPage)
    in RCTView (created by View)
    in View (created by MyPage)
    in MyPage (created by Connect(MyPage))
    in Connect(MyPage) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SceneContent)
    in SceneContent (created by BottomTabView)
    in RCTView (created by View)
    in View (created by ResourceSavingScene)
    in RCTView (created by View)
    in View (created by ResourceSavingScene)
    in ResourceSavingScene (created by BottomTabView)
    in RCTView (created by View)
    in View (created by ScreenContainer)
    in ScreenContainer (created by BottomTabView)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in BottomTabNavigator (created by TabPage)
    in TabPage (created by Connect(TabPage))
    in Connect(TabPage) (created by Connect(TabPage))
    in Connect(TabPage) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RCTView (created by View)
    in View (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in CardStack
    in KeyboardManager (created by SafeAreaInsetsContext)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in StackNavigator (created by AppNavigators)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainer (created by WithBacker)
    in WithBacker (created by AppNavigators)
    in RCTView (created by View)
    in View (created by AppNavigators)
    in AppNavigators (created by Connect(AppNavigators))
    in Connect(AppNavigators)
    in RCTView (created by View)
    in View (created by ModalPanel)
    in ModalPanel (created by ApplicationProvider)
    in ThemeProvider (created by StyleProvider)
    in MappingProvider (created by StyleProvider)
    in StyleProvider (created by ApplicationProvider)
    in ApplicationProvider
    in PersistGate
    in Provider
    in Unknown
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer"
 BUNDLE  ./index.js

**Comment by lirongNISL** [comment]
npm install react-native-color-matrix-image-filters --save  or  yarn add react-native-color-matrix-image-filters
react-native link react-native-color-matrix-image-filters

link后安卓端运行正常，iOS依然报错。如上所示

**Comment by lirongNISL** [comment]
参考 https://github.com/iyegoroff/react-native-color-matrix-image-filters/issues/86

**Comment by lirongNISL** [comment]
iOS
问题1：在 UIManager 中找不到“CMIFColorMatrixImageFilter”

解决方法：
pod 'react-native-color-matrix-image-filters', :path => '../node_modules/react-native-color-matrix-image-filters/react-native-color-matrix-image-filters.podspec'

adding the above code to **podfile** somehow helps

问题2：pod install 后报错：关于 pod install ... dependency were found, but they required a higher minimum deployment target.Specs satisfying the `XXXXX` dependency were found, but they required a higher minimum deployment target.
解决方法：
由于 podfile 里配置的target版本太低，改成platform :ios, '10.0' 或者'11.0',再去 pod install
运行iOS后也正常显示。

**Comment by xclidongbo** [comment]
感谢, 今天解决问题,看到这个坑了.

**Comment by xclidongbo** [comment]
虽然最小支持iOS 11, 但我写iOS 10 打包的情况下, 会导致app闪退不?

**Comment by erayerdin** [comment]
It doesn't work on native Andoid device with Expo. All I did was:

1. install it via `npm i react-native-color-matrix-image-filters`
2. wrap a `ImageBackground` component with `Grayscale`
3. See the error.

```
Invariant Violation: requireNativeComponent: "CMIFColorMatrixImageFilter" was not found in the UIManager.
Invariant Violation: requireNativeComponent: "CMIFColorMatrixImageFilter" was not found in the UIManager.
    at invariant (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:2281:26)
    at getNativeComponentAttributes (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:40715:14)
    at anonymous (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:92791:42)
    at anonymous (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:42243:28)
    at createInstance (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:72076:46)
    at completeWork (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:80780:48)
    at completeUnitOfWork (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:84017:34)
    at performUnitOfWork (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:83993:29)
    at workLoopSync (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:83919:28)
    at renderRootSync (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:83896:25)
    at performSyncWorkOnRoot (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:83621:40)
    at flushSyncCallbacks (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:72813:36)
    at flushSyncCallbacksOnlyInLegacyMode (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:72795:29)
    at scheduleUpdateOnFiber (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:83182:47)
    at dispatchSetState (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:76942:34)
    at ?anon_0_ (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:138283:23)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:5973:26)
    at _next (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:5992:29)
    at tryCallOne (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:15429:26)
    at _callTimer (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:15308:17)
    at _callReactNativeMicrotasksPass (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:15353:17)
    at callReactNativeMicrotasks (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:15559:44)
    at __callReactNativeMicrotasks (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:2857:46)
    at anonymous (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:2631:45)
    at __guard (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:2830:15)
    at flushedQueue (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:2630:21)
    at invokeCallbackAndReturnFlushedQueue (http://192.168.1.20:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true:2624:33)
```

Even downgrading to 5th version does not work.

**Comment by atroudi** [comment]
I have the same error, Any update?
