### ISSUE TITLE
Error with Jest

### ISSUE THREAD

**Issue by SergejDK** [iyegoroff/react-native-color-matrix-image-filters#21]
I try running yarn test or jest but I get the following error:

```
 Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/sergejdick/Projects/ReactNativeFlutterXamarinForms/ReactNativeCompare/node_modules/rn-color-matrices/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Platform, processColor } from 'react-native';
                                                                                                    ^

    SyntaxError: Unexpected token {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (node_modules/react-native-color-matrix-image-filters/src/color-matrix-filter.js:3:1)
```

The jest.config:
```
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|react-native-color-matrix-image-filters)/)"
    ]
  }
```

Maybe this is a stupid failure of me but just started with RN.

RN: 0.60
Newest RNCMIF

**Comment by SergejDK** [comment]
needed to add `rn-color-matrices` to transformIgnorePatterns.

**Comment by bryantobing12** [comment]
@SergejDK still couldn't get this working, could you share your full jest config ?
