### ISSUE TITLE
Pod install fails with new architecture enabled

### ISSUE THREAD

**Issue by GrimDev** [iyegoroff/react-native-color-matrix-image-filters#84]
Hi there,

I've upgrade my RN app to the new architecture with hermes, codegen etc.

`react-native-color-matrix-image-filters` works well on Android, but `RCT_NEW_ARCH_ENABLED=1 pod install` fails with the following error. Works well without new arch enabled but I need it.

```
Error: ENOENT: no such file or directory, lstat '/Users/jev/dev/tellingtone-mobile/node_modules/react-native-color-matrix-image-filters/src'
    at Object.lstatSync (node:fs:1516:3)
    at /Users/jev/dev/tellingtone-mobile/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js:83:10
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/jev/dev/tellingtone-mobile/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js:82:10)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/Users/jev/dev/tellingtone-mobile/node_modules/react-native-color-matrix-image-filters/src'
}
```

It looks like it is searching in the `src` folder that doesn't exists in the release version. Pod install with new arch succeeds when I remove `react-native-color-matrix-image-filters` from my dependencies (via yarn remove).

Here is my rn info :

```
System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 282.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.10.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by iyegoroff** [comment]
fixed in v6.0.1
